//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN
    {
        public GIAOVIEN()
        {
            this.THONGTINDAY = new HashSet<THONGTINDAY>();
        }
    
        public int MA_GV { get; set; }
        public int MA_TT { get; set; }
        public string TENGV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<int> SDT { get; set; }
        public string MATKHAUGV { get; set; }
        public string HINH { get; set; }
        public string MoTa { get; set; }
    
        public virtual TRUNGTAM TRUNGTAM { get; set; }
        public virtual ICollection<THONGTINDAY> THONGTINDAY { get; set; }
    }
}
