//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiaSuEntities : DbContext
    {
        public GiaSuEntities()
            : base("name=GiaSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GIAOVIEN> GIAOVIEN { get; set; }
        public DbSet<HOCVIEN> HOCVIEN { get; set; }
        public DbSet<KHOAHOC> KHOAHOC { get; set; }
        public DbSet<LOPHOC> LOPHOC { get; set; }
        public DbSet<PHONG> PHONG { get; set; }
        public DbSet<THONGTINDAY> THONGTINDAY { get; set; }
        public DbSet<THONGTINLOPHOC> THONGTINLOPHOC { get; set; }
        public DbSet<TRUNGTAM> TRUNGTAM { get; set; }
        public DbSet<CHITIETDANGKY> CHITIETDANGKY { get; set; }
    }
}
