//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HOCVIEN
    {
        public HOCVIEN()
        {
            this.CHITIETDANGKY = new HashSet<CHITIETDANGKY>();
        }
    
        public int MA_HV { get; set; }
        public int MA_KH { get; set; }
        [Required(ErrorMessage ="Bạn cần nhập học tên")]
        public string TEN_HV { get; set; }
        [Required(ErrorMessage = "Bạn cần chọn ngày sinh")]
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập Địa chỉ")]
        public string DIACHI { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập số điện thoại")]
        public Nullable<int> SDT { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập mật khẩu")]
        public string MATKHAUHV { get; set; }
    
        public virtual ICollection<CHITIETDANGKY> CHITIETDANGKY { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
