//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIEN
    {
        public HOCVIEN()
        {
            this.CHITIETDANGKY = new HashSet<CHITIETDANGKY>();
        }
    
        public int MA_HV { get; set; }
        public int MA_KH { get; set; }
        public string TEN_HV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
        public string MATKHAUHV { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
        public virtual ICollection<CHITIETDANGKY> CHITIETDANGKY { get; set; }
    }
}
