//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC
    {
        public KHOAHOC()
        {
            this.HOCVIEN = new HashSet<HOCVIEN>();
            this.LOPHOC = new HashSet<LOPHOC>();
            this.THONGTINDAY = new HashSet<THONGTINDAY>();
        }
    
        public int MA_KH { get; set; }
        public int MA_TT { get; set; }
        public string TEN_KH { get; set; }
        public Nullable<int> THOIGIANHOC { get; set; }
        public Nullable<decimal> HOCPHI { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual ICollection<HOCVIEN> HOCVIEN { get; set; }
        public virtual TRUNGTAM TRUNGTAM { get; set; }
        public virtual ICollection<LOPHOC> LOPHOC { get; set; }
        public virtual ICollection<THONGTINDAY> THONGTINDAY { get; set; }
    }
}
