//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOC
    {
        public LOPHOC()
        {
            this.THONGTINLOPHOC = new HashSet<THONGTINLOPHOC>();
            this.CHITIETDANGKY = new HashSet<CHITIETDANGKY>();
        }
    
        public int MA_LH { get; set; }
        public int MA_KH { get; set; }
        public string TEN_LH { get; set; }
        public Nullable<int> SISO { get; set; }
        public Nullable<bool> BUOI { get; set; }
        public Nullable<bool> NGAY { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
        public virtual ICollection<THONGTINLOPHOC> THONGTINLOPHOC { get; set; }
        public virtual ICollection<CHITIETDANGKY> CHITIETDANGKY { get; set; }
    }
}
