//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.THONGTINLOPHOC = new HashSet<THONGTINLOPHOC>();
        }
    
        public int MA_PHONG { get; set; }
        public Nullable<int> LAU { get; set; }
    
        public virtual ICollection<THONGTINLOPHOC> THONGTINLOPHOC { get; set; }
    }
}
