//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINDAY
    {
        public int MA_KH { get; set; }
        public int MA_GV { get; set; }
        public Nullable<System.DateTime> TGKHAIGIANG { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
